version: "3.7"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8001:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: dashboard_postgres_db
    restart: always
    environment:
      POSTGRES_DB: dashboard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
volumes:
  postgres-data:
  pgadmin-data:
